#     text1 = "  At dusk they pour from the sky.  They blow across the ramparts, turn cartwheels over rooftops, flutter into the ravines between houses.  Entire streets swirl with them, flashing white against the cobbles.  Urgent message to the inhabitants of this town, they say.  Depart immediately to open country. </n>   The tide climbs.  The moon hangs small and yellow and gibbous.  On the rooftops of beachfront hotels to the east, and in the gardens behind them, a half-dozen American artillery units drop incendiary rounds into the mouths of mortars."
# text2 = "  At precisely 5:15 every morning, seven days a week, Dr. Stephen Hellerman emerged from his modest brick colonial in the bucolic town of Silver Spring, Maryland, and jogged six miles.  Six-point-two miles, to be exact. </n>   Depending on whether it was Daylight Saving Time or not, it was either still dark or just dawn as he first stretched his calves against the tall oak shading most of his front yard, but no matter what the season, Dr. Hellerman, an acclaimed neurologist at Mercy Hospital in nearby Langley, rarely saw another human being from start to finish of his run. </n>  That was exactly how he wanted it. </n>  Although he’d never been married, dated sparingly, and socialized with friends even less, it wasn’t that the forty-eight-year-old doctor didn’t like people; he simply liked being alone better.  Being alone meant never being tempted to tell someone your secrets.  And Dr. Stephen Hellerman had a lot of secrets."
# text3 = "  We didn’t like to gossip; we loved to gossip. </n>	Did you hear? </n>	Most of the time, living in Nantucket comforted us; we felt like Mother Ocean was holding us in the palm of her hand.  But sometimes, the island made us restless and irritable.  Winter was bad, but spring was worse, because expect for a few short weeks, it was indistinguishable from winter. </n>	What had T.S. Eliot written?  April is the cruelest month. </n> 	Gossip was always the most rampant in the spring.  It ran like water in a newly thawed brook; it circulated through the air like pollen.  We could no sooner refrain from repeating what we’d heard than we could keep from rubbing our swollen, itchy eyes. </n>	 	We weren’t mean spirited or vindictive or cruel; we were simply bored, and after the long stretch without summer visitors, summer money, summer magic, our reservoirs were dry. </n>		Besides which, we were human beings, saddled with our own curiosities and our own insecurities.  We were aware of things happening in the wider world- human genomes being decoded on the MIT campus, tectonic plates shifting in California, Putin waging war in Ukraine- but none of those events captured our interest like those taking place on the 105 square miles of our home island.  We gossiped at the dentist, in the salon, in the produce section of the Stop & Shop, around the bar at the Boarding House; we gossiped over appetizers at the Anglers’ Club on Friday nights, between the pews of five o’clock Mass on Saturday nights, and in line at the Hub as we waited to buy our New York Times on Sunday mornings."
# text4 = "  None of it would have happened if Spider Barnes hadn’t tied one on at Eddy’s two nights before the Aurora was due to set sail. Spider was regarded as the finest waterborne chef in the entire Caribbean, irascible but altogether irreplaceable, a mad genius in a starched white jacket and apron. Spider, you see, was classically trained. Spider had done a stint in Paris. Spider had done London. Spider had done New York, San Francisco, and an unhappy layover in Miami before leaving the restaurant biz for good and taking to the freedom of the sea. He worked the big charters now, the kind of boats the film stars, rappers, moguls, and poseurs rented whenever they wanted to impress. And when Spider wasn’t behind his stove, he was invariably propped atop one of the better bar stools on dry land. Eddy’s was in his top five in the Caribbean Basin, perhaps his top five worldwide. He started at seven o’clock that evening with a few beers, blew a reefer in the shadowed garden at nine, and at ten was contemplating his first glass of vanilla rum. All seemed right with the world. Spider Barnes was buzzed and in paradise."
# text5 = "  There is a pile of clothing on the side of the train tracks. Light-blue cloth—a shirt, perhaps—jumbled up with something dirty white. It’s probably rubbish, part of a load dumped into the scrubby little wood up the bank. It could have been left behind by the engineers who work this part of the track, they’re here often enough. Or it could be something else. My mother used to tell me that I had an overactive imagination; Tom said that, too. I can’t help it, I catch sight of these discarded scraps, a dirty T-shirt or a lonesome shoe, and all I can think of is the other shoe and the feet that fitted into them.</n>	The train jolts and scrapes and screeches back into motion, the little pile of clothes disappears from view and we trundle on towards London, moving at a brisk jogger’s pace. Someone in the seat behind me gives a sigh of helpless irritation; the 8:04 slow train from Ashbury to Euston can test the patience of the most seasoned commuter. The journey is supposed to take fifty-four minutes, but it rarely does: this section of the track is ancient, decrepit, beset with signaling problems and never-ending engineering works."
# text6 = "  The first argument about money in the Saubers household--the first one the kids overheard, at least—happened on an evening in April.  It wasn’t a big argument, but even the greatest storms begin as gentle breezes.  Peter and Tina Saubers were in the living room, Pete doing homework and Tina watching a Spongebob DVD.  It was one she’d seen before, many times, but she never seemed to tire of it.  This was fortunate, because these days there was no access to the Cartoon Network in the Saubers household.  Tom  Saubers had canceled the cable service two months ago. </n>	Tom and Linda Saubers were in the kitchen, where Tom was cinching his old pack shut after loading it up with PowerBars, a Tupperware filled with cut veggies, two bottles of water, and a can of Coke. “You’re nuts,” Linda said.  “I mean, I’ve always known you were a Type A personality, but this takes it to a whole new level.  If you want to set the alarm for five, fine. You can pick up Todd, be at City Center by six, and you’ll still be first in line.”"
# text7 = "  Even now she can’t decide.  She thinks about flipping a coin.  Heads she goes, tails she stays.  But isn’t indecisiveness an early sign of mental illness?  Didn’t she cover a story about that a few years ago?  Or is it that she’s conflicted?  Conflicted is better than indecisive.  Why is she thinking this way? A voice insider her says, You know damn well why.</n>	She steps up to the bank of phones inside the departure lounge and dials her fifteen-year-old daughter, Eliza, at school, but gets her machine.  She supposes it’s good news that Eliza has gone to her early morning class.  She’ll try again later when she gets there, if she goes.  Otherwise she’ll call from home. </n>	She’s still weighing the pros and cons an hour later when the flight to Newark is announced and the first-class passengers are invited to board.  She feels the panic rising—the dry mouth, the pounding heart, the urge to run.  The mouth of truth.  Once she gets on the plane there will be no turning back.  A hot flash washes over he body.  For god’s sake, not now, she tells herself, wriggling out of her coat.  She takes a deep breath, grabs her carry-on bag and heads for the gate.  She’s going to do this.  She’s not backing down."
# text8 = "  If I have learned anything in this long life of mine, it is this: In love we find out who we want to be; in war we find out who we are.  Today’s young people want to know everything about everyone.  They think talking about a problem will solve it.  I come from a quieter generation.  We understand the value of forgetting, the lure of reinvention. </n>	Lately, though, I find myself thinking about the war and my past, about the people I lost.  Lost.  It makes it sound as if I misplaced my loved ones; perhaps I left them where they don’t belong and then turned away, too confused to retrace my steps. </n>	They are not lost.  Nor are they in a better place.  They are gone.  As I approach the end of my years, I know that grief, like regret, settles into our DNA and remains forever a part of us."
# text9 = "  Thirty-year-old Elaine Marsha Harmon walked briskly from her apartment on East Thirty-Second Street in Manhattan to her job as an assistant interior decorator fifteen blocks away in the Flatiron Building at Twenty-Third Street and Fifth Avenue in Manhattan.  Her coat was warm but she had not worn gloves.  There was a district chill this early November morning.</n> 	She had twisted her long auburn hair and fastened it at the back of her head.  Now only wisps of it blew around her face.  Tall, like her father, and slender, like her mother, she had realized after graduating from college that the life of a teacher was not the way for her to go.  Instead, she enrolled in the Fashion Institute of Technology and after receiving a degree had been hired by Glady Harper, the doyenne of interior decorating among the wealthy and the socially ambitious."
# text10 = "  Be careful how you spend your time.  You never get it back.  Of all the lessons he’d learned from his father, this one truly resonated with Jack Ryan Jr.- no small feat, as he’d received the advice as a teenager with little more on his mind than girls and football games.  Go figure, Jack thought.</n>	In this case, with his lunch appointment predictably late, Jack was playing a round of “watch the watchers,” a game introduced to him by John Clark.  His location, Chaibar, an outdoor café on a quiet Tehran side street, made the game more challenging.  Nestled in the courtyard garden of a renovated villa, Chaibar was full of couples and small groups seated at wrought-iron tables.  Jack caught glimpses of muted flowered murals behind potted plants and hanging vines.  Overhead, boughs cast the courtyard in dappled sunlight.  While most of the murmured voices were speaking Arabic or Persian, Jack also caught snippets of French and Italian."
# text11 = "  My name is Lizzy Tucker, and I live in a small, slightly tilted historic house that sits on a hill overlooking Marblehead Harbor in Massachusetts.  I inherited the house from my Great-Aunt Ophelia when I was twenty-eight, and I’m not much older now.  I share the house with a tiger-striped shorthaired cat.  When he was rescued from the shelter his tag said Cat 7143, and it’s stuck as his name.  Cat has one eye, half a tail, and I’m pretty sure he was a ninja in a past life.  I’m a Johnson & Wales culinary school graduate, and when I’m not being asked to save the world I work as a pastry chef at Dazzle’s Bakery in Salem.</n>	It was ten o’clock at night, Cat and I were watching television in bed, and a big, scruffy, incredibly hot guy walked into my bedroom.</n>	“What the heck?” I asked.  “Where did you come from?” </n>	“Originally? Switzerland, but I was mostly raised in Southern California.”"
# text12 = "  Each morning, the nurses watched him.</n>	At 5:45 a.m., they’d see him step through the hospital’s sliding doors.  By 5:50 a.m., he’d be up among the mechanical beeps and hisses of the ICU.  And by 5:55 a.m., the young man with the boyish looks and sandy hair would approach the nurses’ station, dropping off that day’s breakfast: doughnuts, bagels, sometimes a dozen muffins.</n>	The nurses never made requests for food, but over time the young man had learned that Nurse Tammy liked a pumpernickel bagel with a thin slice of tomato, and that Nurse Steven preferred asiago cheese.  Over these past three weeks of hospital visits, they’d gotten to know him too. Beecher White.</n>		“How’s he doing?” Beecher would ask as he presented his breakfast offering to the hospital gods.</n>	“Same,” the nurses would say on most days, offering kindly smiles and pointing him to Room 355.</n>	The dim room was sealed by sliding glass doors, frosted at the bottom and transparent at the top. For an instant, Beecher paused. The nurses saw it all the time, family and friends picking out which brave face they’d wear that day.</n>	Through the glass was the seventy-two-year-old man with an uneven beard lying unconscious in bed, an accordion breathing tube in his windpipe, a feeding tube snaking through his nose and down into his belly"
# text13 = "  International baggage claim in the Brussels airport was large and airy, with multiple carousels circling endlessly. I scurried from one to another, desperately trying to find my black suitcase. Because it was stuffed with drug money, I was more concerned than one might normally be about lost luggage.</n>	I was twenty-four in 1993 and probably looked like just another anxious young professional woman. My Doc Martens had been jettisoned in favor of beautiful handmade black suede heels. I wore black silk pants and a beige jacket, a typical jeune fille, not a bit countercultural, unless you spotted the tattoo on my neck. I had done exactly as I had been instructed, checking my bag in Chicago through Paris, where I had to switch planes to take a short flight to Brussels.</n>	When I arrived in Belgium, I looked for my black rollie at the baggage claim. It was nowhere to be seen. Fighting a rushing tide of panic, I asked in my mangled high school French what had become of my suitcase. “Bags don’t make it onto the right flight sometime,” said the big lug working in baggage handling. “Wait for the next shuttle from Paris – it’s probably on that plane.”</n>		Had my bag been detected?"
# text14 = "  I come from a country which was created at midnight. When I almost died it was just after midday. One year ago I left my home for school and never returned. I was shot by a Taliban bullet and was flown out of Pakistan unconscious. Some people say I will never return home but I believe firmly in my heart that I will. To be torn from the country that you love is not something to wish on anyone.</n>	Now, every morning when I open my eyes, I long to see my old room full of my things, my clothes all over the floor and my school prizes on the shelves. Instead I am in a country which is five hours behind my beloved homeland Pakistan and my home in the Swat Valley. But my country is centuries behind this one. Here there is any convenience you can imagine. Water running from every tap, hot or cold as you wish; lights at the flick of a switch, day and night, no need for oil lamps; ovens to cook on that don't need anyone to go and fetch gas cylinders from the bazaar. Here everything is so modern one can even find food ready cooked in packets."
# text15 = "  From ancient times and into the Middle Ages, man had dreamed of taking to the sky, of soaring into the blue like the birds.  One savant in Spain in the year 875 is known to have covered himself with feathers in the attempt.  Others devised wings of their own design and jumped from rooftops and towers—some to their deaths—in Constantinople, Nuremberg, Perugia.  Learned monks conceived schemes on paper.  And starting about 1490, Leonardo da Vinci made the most serious studies.  He felt predestined to study flight, he said, and related a childhood memory of a kite flying down onto his cradle.</n>	According to brothers Wilbur and Orville Wright of Dayton, Ohio, it began for them with a toy from France, a small helicopter brought home by their father, Bishop, Milton Wright, a great believer in the educational value of toys.  The creation of a French experimenter of the nineteenth century, Alphonse Pénaud, it was little more than a stick with twin propellers and twisted rubber bands, and probably cost 50 cents.  “Look here, boys,” said the Bishop, something concealed in his hands.  When he let go it flew to the ceiling.  They called it the ‘bat.”"
# text16 = "  On the night of May 6, 1915, as his ship approached the coast of Ireland, Capt. William Thomas Turner left the bridge and made his way to the first-class lounge, where passengers were taking part in a concert and talent show, a customary feature of Cunard crossings.  The room was large and warm, paneled in mahogany and carpeted in green and yellow, with two fourteen-foot-tall fireplaces in the front and rear walls.  Ordinarily Turner avoided events of this kind aboard ship, because he disliked the social obligations of captaincy, but tonight was no ordinary night, and he had news to convey.</n>	There was already a good deal of tension in the room, despite the singing and piano playing and clumsy magic tricks, and this became more pronounced when Turner stepped forward at intermission.  His presence had the perverse effect of affirming everything the passengers had been fearing since their departure from New York, in the way that a priest’s arrival tends to undermine the cheery smile of a nurse."
# text17 = "  The Embassy of the United States to the State of Israel should be a majestic structure.  After all, it is the hub of America’s most special relationship with any foreign nation.  And yet the building—squat and colorless—looks like a bunker.  Perhaps the purpose is to discourage the hundreds of Israelis who daily line the sidewalk outside to apply for tourist visas, or to confound any terrorist who managed to skirt the concrete obstacles girding the grounds.  Whatever its purpose, the bleak exterior reflected my mood as I entered the compound in early June 2009 and presented my passport.</n>	That Yankee-blue document announced that I had been born Michael Bornstein, in Upstate New York and had been a U.S. citizen for more than half a century.  With a faded cover and pages tattooed by customs, it had accompanied me on innumerable transoceanic flights.  Presenting that passport at Newark’s Liberty International Airport, a twenty-minute drive from where my parents raised my two sisters and me, I beamed each time the inspectors wished me, “Welcome home.”"
# text18 = "On March 1, 1781, three and a half years after they were endorsed by the Continental Congress, the Articles of Confederation were officially ratified when the last state, Maryland, gave its approval.  The unseemly delay could be explained by the conspicuous fact that a war was going on, which inevitably deflected attention from all the other business, but the specific reason was that the landless states, like Maryland, refused to ratify until all the states with extensive western claims—Virginia most prominently—agreed to cede their claims to Congress.  The president of the Continental Congress, Samuel Huntington, declared the creation of a new political entity, called the Confederation Congress, which established “a perpetual Union between the thirteen United States.”  To mark the occasion, thirteen cannons were fired from the frigate John Paul Jones."
# text19 = "  I learned about a lot of things in medical school, but mortality wasn’t one of them.   Although I was given a dry, leathery corpse to dissect in my first term, that was solely a way to learn about human anatomy.  Our textbooks had almost nothing on aging or frailty or dying.  How the process unfolds, how people experience the end of their lives, and how it affects those around them seemed beside the point.  The way we saw it, and the way our professors saw it, the purpose of medical schooling was to teach how to save lives, not how to tend to their demise.</n>	The one time I remember discussing mortality was during an hour we spent on The Death of Ivan Ilyich, Tolstoy’s classic novella.  It was in a weekly seminar called Patient-Doctor—part of the school’s effort to make us more rounded and humane physicians.  Some weeks we would practice our physical examination etiquette; other weeks we’d learn about the effects of socioeconomics and race on health.  And one afternoon we contemplated the suffering of Ivan Ilyich as he lay ill and worsening from some unnamed, untreatable disease."
# text20 = "  I became an official Jerry Seinfeld fan the first time he appeared on television on The Merv Griffin Show in 1980.  This was before Seinfeld, of course.  This was back when he was just some guy from Long Island, like me, who talked like me, and cared about the same kinds of things I cared about—and he was the best observational comedian I’d ever seen.</n>	In 1983, I convinced someone in his manager’s office to set up an interview, and not long after, I showed up at his completely unfurnished apartment in West Hollywood.  Thirty years later, I can still see that slightly crestfallen look in his eyes when he opened the door and realized that I was not, in fact, a real journalist from a real radio station with a real audience.  That I was just a fifteen-year-old kid with a tape recorder.</n>		This was one of the most personally influential interviews I did, mainly because he said so many useful things that helped me later in life—it was like a blueprint for how one should go about pursuing career in comedy, and how to write jokes.  For the first time, it dawned on me that comedy is work, and precision and care."
# text21 = "  I looked through the scope of the sniper rifle, scanning down the road of the tiny Iraqi town.  Fifty yards away, a woman opened the door of a small house and stepped outside with her child.</n>	The rest of the street was deserted.  The local Iraqis had gone inside, most of them scared.  A few curious souls peeked out from behind curtains, waiting.  They could hear the rumble of the approaching American unit.  The Marines were flooding up the road, marching north to liberate the country from Saddam Hussein.</n>	It was my job to protect them.  My platoon had taken over the building earlier in the day, sneaking into position to provide “overwatch”—prevent the enemy from ambushing the Marines as they came through."
# text22 = "  At dusk they pour from the sky.  They blow across the ramparts, turn cartwheels over rooftops, flutter into the ravines between houses.  Entire streets swirl with them, flashing white against the cobbles.  Urgent message to the inhabitants of this town, they say.  Depart immediately to open country.</n>	The tide climbs.  The moon hangs small and yellow and gibbous.  On the rooftops of beachfront hotels to the east, and in the gardens behind them, a half-dozen American artillery units drop incendiary rounds into the mouths of mortars."
# text23 = "  Mr. Jones, of the Manor Farm, had locked the hen houses for the night, but was too drunk to remember to shut the popholes.  With the ring of light from his lantern dancing from side to side, he lurched across the yard, kicked off his boots at the back door, drew himself a last glass of beer from the barrel in the scullery, and made his way up to bed, where Mrs. Jones was already snoring.</n> 	As soon as the light in the bedroom went out there was stirring and a fluttering allthrough the farm buildings.  Word had gone round during the day that old Major, the prize Middle White boar, had had a strange dream on the previous night and wished to communicate it to the other animals.  It had been agreed that they should all meet in the big barn as soon as Mr. Jones was safely out of the way.  Old Major (so he was always called, though the name under which he had been exhibited was Willingdon Beauty) was so highly regarded on the farm that everyone was quite ready to lose an hour’s sleep in order to hear what he had to say."
# text24 = "  A throng of bearded men, in sad-colored garments and gray, steeple-crowned hats, intermixed with women, some wearing hoods, and others bareheaded, was assembled in front of a wooden edifice, the door of which was heavily timbered with oak, and studded with iron spikes.</n>	The founders of a new colony, whatever Utopia of human virtue and happiness they might originally project, have invariably recognized it among their earliest practical necessities to allot a portion of the virgin soil as a cemetery, and another portion as the site of a prison. In accordance with this rule, it may safely be assumed that the forefathers of Bostonhad built the first prison-house, somewhere in the vicinity of Cornhill, almost as seasonably as they marked out the first burial-ground, on Isaac Johnson's lot, and round about his grave, which subsequently became the nucleus of all the congregated sepulchres in the old church-yard of King's Chapel. Certain it is, that, some fifteen or twenty years after the settlement of the town, the wooden jail was already marked with weather-stains and other indications of age, which gave a yet darker aspect to its beetle-browed and gloomy front. The rust on the ponderous iron-work of its oaken door looked more antique than any thing else in the new world. Like all that pertains to crime, it seemed never to have known a youthful era. Before this ugly edifice, and between it and the wheel-track of the street, was a grass-plot, much overgrown with burdock, pig-weed, apple-peru, and such unsightly vegetation, which evidently found something congenial in the soil that had so early borne the black flower of civilized society, a prison. But, on one side of the portal, and rooted almost at the threshold, was a wild rose-bush, covered, in this month of June, with its delicate gems, which might be imagined to offer their fragrance and fragile beauty to the prisoner as he went in, and to the condemned criminal as he came forth to his doom, in token that the deep heart of Nature could pity and be kind to him."
# text25 = "  There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question.</n>	I was glad of it: I never liked long walks, especially on chilly afternoons: dreadful to me was the coming home in the raw twilight, with nipped fingers and toes, and a heart saddened by the chidings of Bessie, the nurse, and humbled by the consciousness of my physical inferiority to Eliza, John, and Georgiana Reed. </n>	The said Eliza, John, and Georgiana were now clustered round their mama in the drawing-room: she lay reclined on a sofa by the fireside, and with her darlings about her (for the time neither quarrelling nor crying) looked perfectly happy. Me, she had dispensed from joining the group."
# text26 = "  It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way--in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good.</n>	There were a king with a large jaw and a queen with a plain face, on the throne of England; there were a king with a large jaw and a queen with a fair face, on the throne of France. In both countries it was clearer than crystal to the lords of the State preserves of loaves and fishes, that things in general were settled for ever."
# text27 = "  YOU don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter.  That book was made by Mr. Mark Twain, and he told the truth, mainly.  There was things which he stretched, but mainly he told the truth.  That is nothing.  I never seen anybody but lied one time or another, without it was Aunt Polly, or the widow, or maybe Mary.  Aunt Polly—Tom's Aunt Polly, she is—and Mary, and the Widow Douglas is all told about in that book, which is mostly a true book, with some stretchers, as I said before.</n>	Now the way that the book winds up is this:  Tom and me found the money that the robbers hid in the cave, and it made us rich.  We got six thousand dollars apiece—all gold.  It was an awful sight of money when it was piled up.  Well, Judge Thatcher he took it and put it out at interest, and it fetched us a dollar a day apiece all the year round—more than a body could tell what to do with.  The Widow Douglas she took me for her son, and allowed she would sivilize me; but it was rough living in the house all the time, considering how dismal regular and decent the widow was in all her ways; and so when I couldn't stand it no longer I lit out.  I got into my old rags and my sugar-hogshead again, and was free and satisfied.  But Tom Sawyer he hunted me up and said he was going to start a band of robbers, and I might join if I would go back to the widow and be respectable.  So I went back."
# text28 ="To Mrs. Saville, England</n>St. Petersburgh, Dec. 11th, 17--</n>You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings. I arrived here yesterday, and my first task is to assure my dear sister of my welfare and increasing confidence in the success of my undertaking.</n>  I am already far north of London, and as I walk in the streets of Petersburgh, I feel a cold northern breeze play upon my cheeks, which braces my nerves and fills me with delight. Do you understand this feeling? This breeze, which has travelled from the regions towards which I am advancing, gives me a foretaste of those icy climes. Inspirited by this wind of promise, my daydreams become more fervent and vivid. I try in vain to be persuaded that the pole is the seat of frost and desolation; it ever presents itself to my imagination as the region of beauty and delight. There, Margaret, the sun is forever visible, its broad disk just skirting the horizon and diffusing a perpetual splendour. There--for with your leave, my sister, I will put some trust in preceding navigators-- there snow and frost are banished; and, sailing over a calm sea, we may be wafted to a land surpassing in wonders and in beauty every region hitherto discovered on the habitable globe. Its productions and features may be without example, as the phenomena of the heavenly bodies undoubtedly are in those undiscovered solitudes."
# text29 = "  It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.</n>  However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.</n>  \"My dear Mr. Bennet,'' said his lady to him one day, \"have you heard that Netherfield Park is let at last?\</n>  Mr. Bennet replied that he had not.</n>  \"But it is,'' returned she; \"for Mrs. Long has just been here, and she told me all about it.''</n>  Mr. Bennet made no answer.</n> \"Do not you want to know who has taken it?\" cried his wife impatiently.</n>  \"You want to tell me, and I have no objection to hearing it.\"</n>  This was invitation enough.<n/>  \"Why, my dear, you must know, Mrs. Long says that Netherfield is taken by a young man of large fortune from the north of England; that he came down on Monday in a chaise and four to see the place, and was so much delighted with it that he agreed with Mr. Morris immediately; that he is to take possession before Michaelmas, and some of his servants are to be in the house by the end of next week.\"</n>  \"What is his name?\"</n>  \"Bingley.\"</n>"
# text30 = "  The way I figure it, everyone gets a miracle. Like, I will probably never be struck by lightning, or win a Nobel Prize, or become the dictator of a small nation in the Pacific Islands, or contract terminal ear cancer, or spontaneously combust. But if you consider all the unlikely things together, at least one of them will probably happen to each of us. I could have seen it rain frogs. I could have stepped foot on Mars. I could have been eaten by a whale. I could have married the queen of England or survived months at sea. But my miracle was different. My miracle was this: out of all the houses in all the subdivisions in all of Florida, I ended up living next door to Margo Roth Spiegelman."
# text31 = "  The week before I left my family and Florida and the rest of my minor life to go to boarding school in Alabama, my mother insisted on throwing me a going-away party. To say that I had low expectations would be to underestimate the matter dramatically. Although I was more or less forced to invite all my \"school friends,\" i.e., the ragtag bunch of drama people and English geeks I sat with by social necessity in the cavernous cafeteria of my public school, I knew they wouldn't come. Still, my mother persevered, awash in the delusion that I had kept my popularity secret from her all these years. She cooked a small mountain of artichoke dip. She festooned our living room in green and yellow streamers, the colors of my new school. She bought two dozen champagne poppers and placed them around the edge of our coffee table. "
# text32 = "  First the colors. Then the humans. That's usually how I see things. Or at least, how I try.</n>	***HERE IS A SMALL FACT ***</n>	You are going to die.</n>	I am in all truthfulness attempting to be cheerful about this whole topic, though most people find themselves hindered in believing me, no matter my protestations. Please, trust me. I most definitely can be cheerful. I can be amiable. Agreeable. Affable. And that's only the A's. Just don't ask me to be nice. Nice has nothing to do with me.</n>	***Reaction to the *** AFOREMENTIONED fact Does this worry you? I urge you-don't be afraid. I'm nothing if not fair.  Of course, an introduction.  A beginning.  Where are my manners?</n>	I could introduce myself properly, but it's not really necessary. You will know me well enough and soon enough, depending on a diverse range of variables. It suffices to say that at some point in time, I will be standing over you, as genially as possible. Your soul will be in my arms. A color will be perched on my shoulder. I will carry you gently away.</n>	At that moment, you will be lying there (I rarely find people standing up). You will be caked in your own body. There might be a discovery; a scream will dribble down the air. The only sound I'll hear after that will be my own breathing, and the sound of the smell, of my footsteps. The question is, what color will everything be at that moment when I come for you? What will the sky be saying?</n>	Personally, I like a chocolate-colored sky. Dark, dark chocolate. People say it suits me. I do, however, try to enjoy every color I see-the whole spectrum. A billion or so flavors, none of them quite the same, and a sky to slowly suck on. It takes the edge off the stress. It helps me relax."
# text33 = "  The morning after noted child prodigy Colin Singleton graduated from high school and got dumped for the 19th time by a girl named Katherine, he took a bath. Colin had always preferred baths; one of his general policies in life was never to do anything standing up that could just as easily be done lying down. He climbed into the tub as soon as the water got hot, and he sat and watched with a curiously blank look on his face as the water overtook him. The water inched up his legs, which were crossed and folded into the tub. He did recognize, albeit faintly, that he was too long, and too big, for this bathtub—he looked like a mostly grown person playing at being a kid.</n>	As the water began to splash over his skinny but unmuscled stomach, he thought of Archimedes. When Colin was about four, he read a book about Archimedes, the Greek philosopher who’d discovered you could measure volume by water displacement when he sat down in the bathtub. Upon making this discovery, Archimedes supposedly shouted “Eureka! ” and then ran naked through the streets. The book said that many important discoveries contained a “Eureka moment.” And even then, Colin very much wanted to have some important discoveries, so he asked his mom about it when she got home that evening."
# text34 = "  So in order to understand everything that happened, you have to start from the premise that high school sucks. Do you accept that premise? Of course you do. It is a universally acknowledged truth that high school sucks. In fact, high school is where we are first introduced to the basic existential question of life: How is it possible to exist in a place that sucks so bad?</n>	Most of the time middle school sucks even worse, but middle school is so pathetic that I can’t even bring myself to write about it, so let’s focus on high school.</n>		All right. Allow me to introduce myself: Greg S. Gaines, seventeen. During the period described in this book, I was a senior at Benson High School in lovely inner-city Pittsburgh, Pennsylvania. And before we do anything else, it is necessary for us to examine Benson and the specific ways in which it sucks."
# text35 = "  I had just come to accept that my life would be ordinary when extraordinary things began to happen. The first of these came as a terrible shock and, like anything that changes you forever, split my life into two halves: Before and After. Like many of the extraordinary things to come, it involved my grandfather, Abraham Portman.</n> 	Growing up, Grandpa Portman was the most fascinating person I knew. He had lived in an orphanage, fought in wars, crossed oceans by steamship and deserts on horseback, performed in circuses, knew everything about guns and self-defense and surviving in the wilderness, and spoke at least three languages that weren’t English. It all seems unfathomably exotic to a kid who’d never left Florida, and I begged him to regale me with stories whenever I saw him. He always obliged, telling them like secrets that could be entrusted only to me.</n> 		When I was six I decided that my only chance of having s life half as exciting as Grandpa Portman’s was to become an explorer. He encouraged me by spending afternoons at my side hunched over maps of the world, plotting imaginary expeditions with trails of red pushpins and telling me about the fantastic places I would discover one day."
# text36 = "	A shoebox-shaped package is propped against the front door at an angle. Our front door has a tiny slot to shove mail through, but anything thicker than a bar of soap gets left outside. A hurried scribble on the wrapping addresses the package to Clay Jensen, so I pick it up and head inside.</n> 	I take the package into the kitchen and set it on the counter. I slide open the junk drawer and pull out a pair of scissors. Then I run a scissor blade around the package and lift off its top. Inside the shoebox is a rolled-up tube of bubble wrap. I unroll that and discover seven loose audiotapes."
# text37 = "  I am awake again. Day 6.  Is today a good day to die?  This is something I ask myself in the morning when I wake up. In third period when I’m trying to keep my eyes open while Mr. Schroeder drones on and on. At the supper table as I’m passing the green beans. At night when I’m lying awake because my brain won’t shut off due to all there is to think about.  Is today the day?  And if not today – when?</n> 		I am asking myself this now as I stand on a narrow ledge six stories above the ground. I’s so high up, I’m practically part of the sky. I look down at the pavement below, and the world tilts. I close my eyes, enjoying the way everything spins. Maybe this time I’ll do it – let the air carry me away. It will be like floating in a pool, drifting off until there’s nothing."
# text38 = "  Welcome to the beautiful Sinclair family. No one is a criminal. No one is an addict. No one is a failure. The Sinclairs are athletic, tall, and handsome. WE are old-money Democrats. Our smiles are wide, our chins are square, and our tennis serves aggressive.</n> 	It doesn’t matter if divorce shreds the muscles of our hearts so that they will hardly beat without a struggle. It doesn’t matter if trust-fund money is running out; if credit card bills go unpaid on the kitchen counter. It doesn’t matter if there’s a cluster of pill bottles on the bedside table. It doesn’t matter if one of us is desperately, desperately in love.</n> 		So much in love that equally desperate measures must be taken. We are Sinclairs. No one is needy. No one is wrong. We live, at least in the summertime, on a private island off the coast of Massachusetts.</n> Perhaps that is all you need to know."
# text39 = "  I hate First Friday. It makes the village crowded, and now, in the heat of the high summer, that’s the last thing anyone wants. From my place in the shade it isn’t so bad, but the sink of bodies, all sweating with the morning work, is enough to make milk curdle. The air shimmers with heat and humidity, and even the puddles from yesterday’s storm are hot, swirling with rainbow streaks of oil and grease.</n> 		The market deflates, with everyone closing up their wares. By the time I’m done, my pockets bulge with trinkets and I’ve got an apple for the road. Not bad for a minute’s work. As the throng of people moves, I let myself be taken away by the human current. My hands dart in and out, always fleeting touches. Some paper bills from a man’s pocket, a bracelet from a woman’s wrist – nothing too big. Villagers are too busy shuffling along to notice a pickpocket in their midst."

# $books = {text1 => {:author => "Anthony Doerr",
#   :title => "All the Lights We Cannot See",
#   :image => "http://mediad.publicbroadcasting.net/p/kuer/files/201406/all-the-light-we-cannot-see-9781476746586_hr_0.jpg",
#   :link => "http://www.amazon.com/All-Light-We-Cannot-See/dp/1476746583/ref=sr_1_1?ie=UTF8&qid=1437100647&sr=8-1&keywords=all+the+light+we+cannot+see&pebp=1437100679668&perid=0M6ATE01J4S382HW8BVC"},
#   text2 => {:author => "James Patterson",
#              :title => "Truth or Die",
#   :image => "http://ecx.images-amazon.com/images/I/51ddvXE-H5L._SY344_BO1,204,203,200_.jpg",
#   :link => "http://www.amazon.com/Truth-Die-James-Patterson/dp/0316407011/ref=sr_1_1?ie=UTF8&qid=1437100747&sr=8-1&keywords=truth+or+die"},
#   text3 => {:author => "Elin Hilderbrand",
#              :title => "The Rumor",
#   :image => "http://ecx.images-amazon.com/images/I/51Ny5-y08NL._SX321_BO1,204,203,200_.jpg",
#   :link => "http://www.amazon.com/Rumor-Novel-Elin-Hilderbrand/dp/0316334529/ref=sr_1_1?ie=UTF8&qid=1437100772&sr=8-1&keywords=the+rumor&pebp=1437100775071&perid=06NFCDKWS60V8CD7Q2ET"},
#   text4 => {:author => "Daniel Silva",
#              :title => "The English",
#   :image => "http://danielsilvabooks.com/wordpress/wp-content/uploads/2015/01/TESCover_WebsiteSize.jpg",
#   :link => "http://www.amazon.com/English-Spy-Daniel-Silva/dp/0062320130/ref=sr_1_1?ie=UTF8&qid=1437100799&sr=8-1&keywords=the+english+spy&pebp=1437100806045&perid=1D54YM2G2VTFNC2RR557"},
#   text5 => {:author => "Paula Hawkins",
#             :title => "The Girl on the Train",
#   :image => "http://ecx.images-amazon.com/images/I/91lUeBR2G1L.jpg",
#   :link => "http://www.amazon.com/Girl-Train-Paula-Hawkins/dp/1594633665/ref=sr_1_1?ie=UTF8&qid=1437100826&sr=8-1&keywords=the+girl+on+the+train&pebp=1437100828551&perid=0CFTWEJEHN6RQS6WE7B1"},
#   text6 => {:author => "Stephen King",
#              :title => "Finders Keepers",
#   :image => "http://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781501100079/finders-keepers-9781501100079_hr.jpg",
#   :link => "http://www.amazon.com/Finders-Keepers-Novel-Stephen-King/dp/1501100076/ref=sr_1_1?ie=UTF8&qid=1437100854&sr=8-1&keywords=finders+keepers"},
#   text7 => {:author => "Judy Blume",
#              :title => "In the Unlikely Event",
#   :image => "http://assets.nydailynews.com/polopoly_fs/1.2047043.1418747922!/img/httpImage/image.jpg_gen/derivatives/article_970/blume17f-2-web.jpg?enlarged",
#   :link => "http://www.amazon.com/Unlikely-Event-Judy-Blume/dp/1101875046/ref=sr_1_1?ie=UTF8&qid=1437100872&sr=8-1&keywords=in+the+unlikely+event&pebp=1437100873983&perid=0SVZEMXNWEAMNYQYEE6W"},
#   text8 => {:author => "Kristen Hannah",
#               :title => "The Nightingale",
#   :image => "http://ecx.images-amazon.com/images/I/81j3rfXRwmL.jpg",
#   :link => "http://www.amazon.com/Nightingale-Kristin-Hannah/dp/0312577222/ref=sr_1_1?ie=UTF8&qid=1437101010&sr=8-1&keywords=the+nightingale&pebp=1437101011514&perid=18VTS28QRMFGQ7N1H3WC"},
#   text9 => {:author => "Mary Higgins Clark",
#     :title => "The Melody Lingers On",
#   :image => "http://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781471148521/the-melody-lingers-on-9781471148521_hr.jpg",
#   :link => "http://www.amazon.com/Melody-Lingers-Mary-Higgins-Clark/dp/1476749116/ref=sr_1_1?ie=UTF8&qid=1437101030&sr=8-1&keywords=the+melody+lingers&pebp=1437101031851&perid=0TGSQB8M2G4DEZXH6EEZ"},
#   text10 => {:author => "Grant Blackwood",
#               :title => "Tom Clancy Under Fire",
#   :image => "http://images.booksense.com/images/811/480/9781410480811.jpg",
#   :link => "http://www.amazon.com/Clancy-Under-Fire-Jack-Novel/dp/039917575X/ref=sr_1_1?ie=UTF8&qid=1437101072&sr=8-1&keywords=tom+clancy+under+fire&pebp=1437101073784&perid=0JZ0ZM60H02K2JN1FQKH"},
#   text11 => {:author => "Phoef Sutton",
#               :title => "Wicked Charms",
#   :image => "http://ecx.images-amazon.com/images/I/51uZlcQonvL._SX329_BO1,204,203,200_.jpg",
#   :link => "http://www.amazon.com/Wicked-Charms-Lizzy-Diesel-Novel/dp/0553392719/ref=sr_1_1?ie=UTF8&qid=1437101095&sr=8-1&keywords=wicked+charms&pebp=1437101096365&perid=1A0FA9BSBA42VSAC172H"},
#   text12 => {:author => "Brad Meltzer",
#               :title => "The President's Shadow",
#   :image => "http://3.bp.blogspot.com/-4XtRMnbTSM0/VX-kQWndG7I/AAAAAAAAAlo/vtpgOX7m_bE/s1600/Meltzer_ThePresidentsShadow%2528HC%2529.JPG",
#   :link => "http://www.amazon.com/Presidents-Shadow-Culper-Ring/dp/044655393X/ref=sr_1_1?ie=UTF8&qid=1437101117&sr=8-1&keywords=the+president%27s+shadow&pebp=1437101118134&perid=0GV98W3691C88RH0MEHY"},
#   text13 => {:author => "Piper Kerman",
#               :title => "Orange is the New Black",
#   :image => "http://lonetreeartscenter.org/images/shows/1399326316_heading_image_Orange_is_the_New_Black%20Cover.jpg",
#   :link => "http://www.amazon.com/Orange-New-Black-Womens-Prison/dp/0385523394/ref=sr_1_2?ie=UTF8&qid=1437101141&sr=8-2&keywords=orange+is+the+new+black&pebp=1437101145712&perid=162K1Y74K9PH026JE5MR"},
#   text14 => {:author => "Malala Yousafzai",
#               :title => "I am Malala",
#   :image => "http://www.growpk.com/wp-content/uploads/2013/10/i-am-malala.png",
#   :link => "http://www.amazon.com/Am-Malala-Stood-Education-Taliban/dp/0316322423/ref=sr_1_1?ie=UTF8&qid=1437101168&sr=8-1&keywords=i+am+malala&pebp=1437101169579&perid=1CWR7CN23HSGCN09B16V"},
#   text15 => {:author => "David McCullough",
#               :title => "The Wright Brothers",
#   :image => "http://www.gannett-cdn.com/-mm-/f9c56189b2707e4e79d9308ecb44a51270534ead/c=0-13-288-398&r=537&c=0-0-534-712/local/-/media/2015/02/13/USATODAY/USATODAY/635594341739927965-Wright-Brothers---Cover-ARt.jpg",
#   :link => "http://www.amazon.com/Wright-Brothers-David-McCullough/dp/1476728747/ref=sr_1_1?ie=UTF8&qid=1437101192&sr=8-1&keywords=the+wright+brothers+david+mccullough"},
#   text16 => {:author => "Erik Larson",
#               :title => "Dead Wake",
#   :image => "http://media.npr.org/assets/bakertaylor/covers/d/dead-wake/9780307408860_custom-a80e1228d0198d00e5edade52e3ea6bce83e7410-s1200-c15.jpg",
#   :link => "http://www.amazon.com/Dead-Wake-Last-Crossing-Lusitania/dp/0307408868/ref=sr_1_1?ie=UTF8&qid=1437101208&sr=8-1&keywords=dead+wake&pebp=1437101210342&perid=15QXYH9KDM1SN9QJHW0A"},
#   text17 => {:author => "Michael B. Oren",
#               :title => "Ally",
#   :image => "http://si.wsj.net/public/resources/images/BN-JA647_bkrvor_JV_20150622123106.jpg",
#   :link => "http://www.amazon.com/Ally-Journey-Across-American-Israeli-Divide/dp/0812996410/ref=sr_1_1?ie=UTF8&qid=1437101238&sr=8-1&keywords=ally+michael+oren&pebp=1437101242100&perid=0TY6XP7FCC7KZ23TJQ5T"},
#   text18 => {:author => "Joseph J. Ellis",
#               :title => "The Quartet",
#   :image => "http://ecx.images-amazon.com/images/I/51TXZtZRl1L._SX342_BO1,204,203,200_.jpg",
#   :link => "http://www.amazon.com/Quartet-Orchestrating-American-Revolution-1783-1789/dp/0385353405/ref=sr_1_1?ie=UTF8&qid=1437101261&sr=8-1&keywords=the+quartet&pebp=1437101261904&perid=0XW1CBBV7JKE7H2WVSY2"},
#   text19 => {:author => "Atul Gawande",
#               :title => "Being Mortal",
#   :image => "http://www.gannett-cdn.com/-mm-/388d498716ac772af066fe922dcc5f78343e9e97/c=0-58-662-941&r=537&c=0-0-534-712/local/-/media/Clarksville/2015/01/02/B9315716992Z.1_20150102131310_000_G479IMJ8A.1-0.jpg",
#   :link => "http://www.amazon.com/Being-Mortal-Medicine-What-Matters/dp/0805095152/ref=sr_1_1?ie=UTF8&qid=1437101278&sr=8-1&keywords=being+mortal&pebp=1437101279885&perid=1YREP6V89B0T0YGER320"},
#   text20 => {:author => "Judd Apatow",
#               :title => "Sick in the Head",
#   :image => "http://images2.eruditetechnologies.com.au/original/readings/978/085/798/9780857985927.jpg",
#   :link => "http://www.amazon.com/Sick-Head-Conversations-About-Comedy/dp/0812997573/ref=sr_1_1?ie=UTF8&qid=1437101298&sr=8-1&keywords=sick+in+the+head&pebp=1437101299493&perid=0Q7NM2SPF1QH1EWW78BA"},
#   text21 => {:author => "Chris Kyle",
#               :title => "American Sniper",
#   :image => "http://ecx.images-amazon.com/images/I/71bmwJ6z--L.jpg",
#   :link => "http://www.amazon.com/American-Sniper-Autobiography-Military-History/dp/0062238868/ref=sr_1_1?ie=UTF8&qid=1437101314&sr=8-1&keywords=american+sniper+book&pebp=1437101323134&perid=15J1JJRYB2RTCRJCZR0V"},
#   text23 => {:author => "George Orwell",
#               :title => "Animal Farm",
#   :image => "https://www.penguin.com.au/jpg-large/9780141036137.jpg",
#   :link => "http://www.amazon.com/Animal-Farm-Anniversary-George-Orwell/dp/0451526341/ref=sr_1_1?s=books&ie=UTF8&qid=1437101411&sr=1-1&keywords=animal+farm&pebp=1437101412597&perid=1BNNZNZY1BH2GG516SS2"},
#   text24 => {:author => "Nathaniel Hawthorne",
#               :title => "The Scarlet Letter",
#   :image => "http://ecx.images-amazon.com/images/I/51E-lPPSn2L._SY344_BO1,204,203,200_.jpg",
#   :link => "http://www.amazon.com/Animal-Farm-Anniversary-George-Orwell/dp/0451526341/ref=sr_1_1?s=books&ie=UTF8&qid=1437101411&sr=1-1&keywords=animal+farm&pebp=1437101412597&perid=1BNNZNZY1BH2GG516SS2"},
#   text25  => {:author => "Charlotte Bronte",
#                :title => "Jane Eyre",
#   :image => "http://goodtoread.org/image/covers/jane-eyre.jpg",
#   :link => "http://www.amazon.com/Jane-Eyre-Charlotte-Bronte/dp/1503278190/ref=sr_1_1?s=books&ie=UTF8&qid=1437101453&sr=1-1&keywords=jane+eyre&pebp=1437101457009&perid=0M9J273PYG0SNG84QD2F"},
#   text26 => {:author => "Charles Dickens",
#               :title => "A Tale of Two Cities",
#   :image => "http://i43.tower.com/images/mm100631304/a-tale-two-cities-charles-dickens-paperback-cover-art.jpg",
#   :link => "http://www.amazon.com/Tale-Cities-Dover-Thrift-Editions/dp/0486406512/ref=sr_1_1?s=books&ie=UTF8&qid=1437101476&sr=1-1&keywords=a+tale+of+two+cities&pebp=1437101479266&perid=02HMVHAYW3B1RW9EEDE3"},
#   text27 => {:author => "Mark Twain",
#              :title => "The Adventures of Huckleberry Finn",
#   :image => "http://www.bradleysbookoutlet.com/wp-content/uploads/2013/09/huck-finn.jpg",
#   :link => "http://www.amazon.com/Adventures-Huckleberry-Finn-Mark-Twain/dp/0486280616/ref=sr_1_1?s=books&ie=UTF8&qid=1437101502&sr=1-1&keywords=adventures+of+huckleberry+finn&pebp=1437101504133&perid=0VFT0KGT13MCGRGS91DJ"},
#   text28 => {:author => "Mary Shelley",
#               :title => "Frankenstein",
#   :image => "https://theworldoffrankenstein.files.wordpress.com/2012/04/frankenstein_book_cover_01.jpg",
#   :link => "http://www.amazon.com/Frankenstein-Mary-Shelley/dp/0486282112/ref=sr_1_1?s=books&ie=UTF8&qid=1437101520&sr=1-1&keywords=frankenstein&pebp=1437101521388&perid=0ED19AEY3G1PCBTHZRVS"},
#   text29 => {:author => "Jane Austen",
#               :title => "Pride and Prejudice",
#   :image => "https://apilgriminnarnia.files.wordpress.com/2015/01/austen-pride-and-prejudice1946.jpg",
#   :link => "http://www.amazon.com/Pride-Prejudice-Jane-Austen/dp/1503290565/ref=sr_1_1?s=books&ie=UTF8&qid=1437101541&sr=1-1&keywords=pride+and+prejudice"},
#   text30 => {:author => "John Green",
#               :title => "Paper Towns",
#   :image => "http://www.uncanny.ch/wp-content/uploads/2015/06/paper_towns_john_green_cover.jpg",
#   :link => "http://www.amazon.com/Paper-Towns-John-Green/dp/014241493X/ref=sr_1_1?s=books&ie=UTF8&qid=1437101557&sr=1-1&keywords=paper+towns&pebp=1437101558682&perid=03NZ8V4K9NJNTY2XZ1B4"},
#   text31 => {:author => "John Green",
#               :title => "Looking for Alaska",
#   :image => "http://www.ala.org/yalsa/sites/all/files/content/yalsa/printz/alaska.jpg",
#   :link => "http://www.amazon.com/Looking-Alaska-John-Green/dp/0142402516/ref=sr_1_1?s=books&ie=UTF8&qid=1437101626&sr=1-1&keywords=looking+for+alaska+by+john+green&pebp=1437101628955&perid=1WB65FN0311F05ZT40NX "},
#   text32 => {:author => "Markus Zusak",
#               :title => "The Book Thief",
#   :image => "http://ecx.images-amazon.com/images/I/81Rsqc%2Bi8WL.jpg",
#   :link => "http://www.amazon.com/Book-Thief-Markus-Zusak/dp/0375842209/ref=sr_1_1?s=books&ie=UTF8&qid=1437101660&sr=1-1&keywords=the+book+thief&pebp=1437101661061&perid=1DCR2JRPJ9HE0VKHQ2F7"},
#   text33 => {:author => "John Green",
#               :title => "An Abundance of Katherines",
#   :image => "https://shelfmadegirl.files.wordpress.com/2013/07/9780142410707_custom-937c8a14ae3737ec420c733288cba59afd9f1ce3-s6-c30.jpg",
#   :link => "http://www.amazon.com/Abundance-Katherines-John-Green/dp/0142410705/ref=sr_1_1?s=books&ie=UTF8&qid=1437101726&sr=1-1&keywords=an+abundance+of+katherines&pebp=1437101736262&perid=0FPZQ1ZHXDSEN1VN74QS"},
#   text34 => {:author => "Jesse Andrews",
#              :title => "Me and Earl and the Dying Girl",
#   :image => "http://idiosyncraticlibrary.com/wp-content/uploads/2015/06/Me-and-Earl-and-the-Dying-girl.jpg",
#   :link => "http://www.amazon.com/Me-Earl-Dying-Girl-Revised/dp/1419719602/ref=sr_1_1?s=books&ie=UTF8&qid=1437101772&sr=1-1&keywords=me+and+earl+and+the+dying+girl&pebp=1437101777897&perid=166SH3W2QHXXQT1C0C3S"},
#   text35 => {:author => "Ransom Riggs",
#               :title => "Miss Peregrine's Home for Peculiar Children",
#   :image => "http://www.quirkbooks.com/sites/default/files/book_covers/missp_NYTcover%231_300dpi.jpg",
#   :link => "http://www.amazon.com/Miss-Peregrines-Home-Peculiar-Children/dp/1594746036/ref=sr_1_1?s=books&ie=UTF8&qid=1437101799&sr=1-1&keywords=miss+peregrine%27s+home+for+peculiar+children&pebp=1437101801051&perid=04Z5TYNYV11PRGNHET0S"},
#   text36 => {:author => "Jay Asher",
#               :title => "Thirteen Reasons Why",
#   :image => "https://adventuresofawanderingmind.files.wordpress.com/2013/09/thirteen-reasons-why.jpg",
#   :link => "http://www.amazon.com/Thirteen-Reasons-Why-Jay-Asher/dp/159514188X/ref=sr_1_1?s=books&ie=UTF8&qid=1437101820&sr=1-1&keywords=thirteen+reasons+why&pebp=1437101822496&perid=1M1H6NYSZC2TSJPK18J4"},
#   text37 => {:author => "Jennifer Niven",
#               :title => "All the Bright Places",
#   :image => "https://www.penguin.com.au/jpg-large/9780141357034.jpg",
#   :link => "http://www.amazon.com/All-Bright-Places-Jennifer-Niven/dp/0385755880/ref=sr_1_1?s=books&ie=UTF8&qid=1437101848&sr=1-1&keywords=all+the+bright+places"},
#   text38 => {:author => "E. Lockhart",
#               :title => "We Were Liars",
#   :image => "http://ecx.images-amazon.com/images/I/91cMHG1mVaL.jpg",
#   :link => "http://www.amazon.com/We-Were-Liars-E-Lockhart/dp/038574126X/ref=sr_1_1?s=books&ie=UTF8&qid=1437101865&sr=1-1&keywords=we+were+liars&pebp=1437101867184&perid=0Z0ETV8N5XH2B4MHB4M6"},
#   text39 => {:author => "Victoria Aveyard",
#               :title => "Red Queen",
#   :image => "http://www.hollywoodreporter.com/sites/default/files/2014/06/red_queen_book_cover_a_p.jpg",
#   :link => "http://www.amazon.com/Red-Queen-Victoria-Aveyard/dp/0062310631/ref=sr_1_1?s=books&ie=UTF8&qid=1437101892&sr=1-1&keywords=red+queen&pebp=1437101893700&perid=0WAY92ATDRAV1CSCHZ5F"}
      
#   }